<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Binary Logistic Regression | Quantitative Foundations in Educational Research</title>
  <meta name="description" content="This is for course ESC_PS 8850 at the University of Missouri. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Binary Logistic Regression | Quantitative Foundations in Educational Research" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is for course ESC_PS 8850 at the University of Missouri. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="ze-wang/quant-foundations" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Binary Logistic Regression | Quantitative Foundations in Educational Research" />
  
  <meta name="twitter:description" content="This is for course ESC_PS 8850 at the University of Missouri. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Ze Wang" />


<meta name="date" content="2021-07-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-regression-analysis.html"/>
<link rel="next" href="analysis-of-variance.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i>Contents</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#the-r-language"><i class="fa fa-check"></i><b>1.1</b> The R Language</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#why-r"><i class="fa fa-check"></i><b>1.1.1</b> Why R?</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#statistical-analysis-software-for-data-modeling"><i class="fa fa-check"></i><b>1.1.2</b> Statistical analysis software for data modeling</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#install-r"><i class="fa fa-check"></i><b>1.2</b> Install R</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#install-rstudio"><i class="fa fa-check"></i><b>1.3</b> Install RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#use-rstudio"><i class="fa fa-check"></i><b>1.4</b> Use RStudio</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#basic-operations"><i class="fa fa-check"></i><b>1.4.1</b> Basic operations</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#data-types-in-r"><i class="fa fa-check"></i><b>1.4.2</b> Data types in R</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#data-structures-in-r"><i class="fa fa-check"></i><b>1.4.3</b> Data structures in R</a></li>
<li class="chapter" data-level="1.4.4" data-path="intro.html"><a href="intro.html#packages"><i class="fa fa-check"></i><b>1.4.4</b> R packages</a></li>
<li class="chapter" data-level="1.4.5" data-path="intro.html"><a href="intro.html#rstudio-projects"><i class="fa fa-check"></i><b>1.4.5</b> RStudio projects</a></li>
<li class="chapter" data-level="1.4.6" data-path="intro.html"><a href="intro.html#import-and-export-data"><i class="fa fa-check"></i><b>1.4.6</b> Import and export Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html"><i class="fa fa-check"></i><b>2</b> Review of Basic Statistics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#calculating-variance-and-covariance"><i class="fa fa-check"></i><b>2.1</b> Calculating Variance and Covariance</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#covariance"><i class="fa fa-check"></i><b>2.1.1</b> Covariance</a></li>
<li class="chapter" data-level="2.1.2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#correlation"><i class="fa fa-check"></i><b>2.1.2</b> Correlation</a></li>
<li class="chapter" data-level="2.1.3" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#using-matrix-algebra"><i class="fa fa-check"></i><b>2.1.3</b> Using Matrix Algebra</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#basic"><i class="fa fa-check"></i><b>2.2</b> Use R for Basic Statistics</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#import-and-export-data-1"><i class="fa fa-check"></i><b>2.2.1</b> Import and export data</a></li>
<li class="chapter" data-level="2.2.2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#several-functions-for-basic-data-management"><i class="fa fa-check"></i><b>2.2.2</b> Several functions for basic data management</a></li>
<li class="chapter" data-level="2.2.3" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#some-descriptive-statistics"><i class="fa fa-check"></i><b>2.2.3</b> Some descriptive statistics</a></li>
<li class="chapter" data-level="2.2.4" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#check-normality"><i class="fa fa-check"></i><b>2.2.4</b> Check normality</a></li>
<li class="chapter" data-level="2.2.5" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#check-linearity"><i class="fa fa-check"></i><b>2.2.5</b> Check linearity</a></li>
<li class="chapter" data-level="2.2.6" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#pearsons-product-moment-correlation"><i class="fa fa-check"></i><b>2.2.6</b> Pearson’s product moment correlation</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-r-for-graphing-data"><i class="fa fa-check"></i><b>2.3</b> Use R for Graphing Data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-plot"><i class="fa fa-check"></i><b>2.3.1</b> Use <code>plot()</code></a></li>
<li class="chapter" data-level="2.3.2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-ggplot2-package"><i class="fa fa-check"></i><b>2.3.2</b> Use <code>ggplot2</code> package</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-r-to-graph-a-correlation-matrix"><i class="fa fa-check"></i><b>2.4</b> Use R to Graph a Correlation Matrix</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-plot-1"><i class="fa fa-check"></i><b>2.4.1</b> Use <code>plot()</code></a></li>
<li class="chapter" data-level="2.4.2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-ggplot"><i class="fa fa-check"></i><b>2.4.2</b> Use <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#use-r-to-generate-random-data"><i class="fa fa-check"></i><b>2.5</b> Use R to Generate Random Data</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#sampling-distribution"><i class="fa fa-check"></i><b>2.5.1</b> Sampling distribution</a></li>
<li class="chapter" data-level="2.5.2" data-path="review-of-basic-statistics.html"><a href="review-of-basic-statistics.html#simulate-data-from-a-model"><i class="fa fa-check"></i><b>2.5.2</b> Simulate data from a model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-1.html"><a href="correlation-1.html"><i class="fa fa-check"></i><b>3</b> Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="correlation-1.html"><a href="correlation-1.html#variance-and-covariance"><i class="fa fa-check"></i><b>3.1</b> Variance and Covariance</a></li>
<li class="chapter" data-level="3.2" data-path="correlation-1.html"><a href="correlation-1.html#pearson-product-moment-correlation-pearson-correlation"><i class="fa fa-check"></i><b>3.2</b> Pearson Product-Moment Correlation (Pearson Correlation)</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="correlation-1.html"><a href="correlation-1.html#test-that-the-population-correlation-equals-zero"><i class="fa fa-check"></i><b>3.2.1</b> Test that the population correlation equals zero</a></li>
<li class="chapter" data-level="3.2.2" data-path="correlation-1.html"><a href="correlation-1.html#check-normality-1"><i class="fa fa-check"></i><b>3.2.2</b> Check normality</a></li>
<li class="chapter" data-level="3.2.3" data-path="correlation-1.html"><a href="correlation-1.html#check-for-linearity-with-scatterplot"><i class="fa fa-check"></i><b>3.2.3</b> Check for linearity with scatterplot</a></li>
<li class="chapter" data-level="3.2.4" data-path="correlation-1.html"><a href="correlation-1.html#factors-that-affect-the-pearson-correlation"><i class="fa fa-check"></i><b>3.2.4</b> Factors that affect the Pearson Correlation</a></li>
<li class="chapter" data-level="3.2.5" data-path="correlation-1.html"><a href="correlation-1.html#test-that-the-population-correlation-equals-a-certain-value"><i class="fa fa-check"></i><b>3.2.5</b> Test that the population correlation equals a certain value</a></li>
<li class="chapter" data-level="3.2.6" data-path="correlation-1.html"><a href="correlation-1.html#test-that-two-population-correlations-are-equal"><i class="fa fa-check"></i><b>3.2.6</b> Test that two population correlations are equal</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="correlation-1.html"><a href="correlation-1.html#variations-of-the-pearson-product-moment-correlation"><i class="fa fa-check"></i><b>3.3</b> Variations of the Pearson Product-Moment Correlation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="correlation-1.html"><a href="correlation-1.html#point-biserial-correlation"><i class="fa fa-check"></i><b>3.3.1</b> Point Biserial Correlation</a></li>
<li class="chapter" data-level="3.3.2" data-path="correlation-1.html"><a href="correlation-1.html#biserial-correlation"><i class="fa fa-check"></i><b>3.3.2</b> Biserial Correlation</a></li>
<li class="chapter" data-level="3.3.3" data-path="correlation-1.html"><a href="correlation-1.html#spearmans-rankspearmans-correlationspearmans-rho"><i class="fa fa-check"></i><b>3.3.3</b> Spearman’s Rank/Spearman’s Correlation/Spearman’s rho</a></li>
<li class="chapter" data-level="3.3.4" data-path="correlation-1.html"><a href="correlation-1.html#phi-coefficient"><i class="fa fa-check"></i><b>3.3.4</b> Phi Coefficient</a></li>
<li class="chapter" data-level="3.3.5" data-path="correlation-1.html"><a href="correlation-1.html#tetrachoric-correlation"><i class="fa fa-check"></i><b>3.3.5</b> Tetrachoric Correlation</a></li>
<li class="chapter" data-level="3.3.6" data-path="correlation-1.html"><a href="correlation-1.html#polychoric-correlation"><i class="fa fa-check"></i><b>3.3.6</b> Polychoric Correlation</a></li>
<li class="chapter" data-level="3.3.7" data-path="correlation-1.html"><a href="correlation-1.html#chi-square"><i class="fa fa-check"></i><b>3.3.7</b> Chi-Square</a></li>
<li class="chapter" data-level="3.3.8" data-path="correlation-1.html"><a href="correlation-1.html#summary-of-measures-of-association"><i class="fa fa-check"></i><b>3.3.8</b> Summary of measures of association</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="correlation-1.html"><a href="correlation-1.html#an-example"><i class="fa fa-check"></i><b>3.4</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>4</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#plot-the-data"><i class="fa fa-check"></i><b>4.1</b> Plot the Data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#using-plot"><i class="fa fa-check"></i><b>4.1.1</b> Using <code>plot()</code></a></li>
<li class="chapter" data-level="4.1.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#using-ggplot"><i class="fa fa-check"></i><b>4.1.2</b> Using <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#the-regression-equation"><i class="fa fa-check"></i><b>4.2</b> The Regression Equation</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#variance-explained"><i class="fa fa-check"></i><b>4.2.1</b> Variance explained</a></li>
<li class="chapter" data-level="4.2.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#relationship-with-pearson-correlation"><i class="fa fa-check"></i><b>4.2.2</b> Relationship with Pearson correlation</a></li>
<li class="chapter" data-level="4.2.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#coefficient-of-determination-r2"><i class="fa fa-check"></i><b>4.2.3</b> Coefficient of Determination (<span class="math inline">\({{R}^{2}}\)</span>)</a></li>
<li class="chapter" data-level="4.2.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#r-syntax"><i class="fa fa-check"></i><b>4.2.4</b> R Syntax</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#test-of-significance-and-confidence-interval"><i class="fa fa-check"></i><b>4.3</b> Test of Significance and Confidence Interval</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-the-regression-of-y-on-x"><i class="fa fa-check"></i><b>4.3.1</b> Testing the regression of Y on X</a></li>
<li class="chapter" data-level="4.3.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-the-regression-coefficient-slope-and-the-confidence-interval"><i class="fa fa-check"></i><b>4.3.2</b> Testing the regression coefficient (slope) and the confidence interval</a></li>
<li class="chapter" data-level="4.3.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#r-syntax-1"><i class="fa fa-check"></i><b>4.3.3</b> R Syntax</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#summary-of-important-statistics"><i class="fa fa-check"></i><b>4.4</b> Summary of Important Statistics</a></li>
<li class="chapter" data-level="4.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#confidence-intervals-hypothesis-testing-and-prediction-intervals"><i class="fa fa-check"></i><b>4.5</b> Confidence Intervals, Hypothesis Testing, and Prediction Intervals</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#prediction-intervals-for-new-observations"><i class="fa fa-check"></i><b>4.5.1</b> Prediction Intervals for New Observations</a></li>
<li class="chapter" data-level="4.5.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#r-syntax-2"><i class="fa fa-check"></i><b>4.5.2</b> R Syntax</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#a-complete-example"><i class="fa fa-check"></i><b>4.6</b> A Complete Example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html"><i class="fa fa-check"></i><b>5</b> Multiple Regression Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#f-test-and-partial-f-test"><i class="fa fa-check"></i><b>5.1</b> F Test and Partial F Test</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#overall-test-f-test"><i class="fa fa-check"></i><b>5.1.1</b> Overall test (F Test)</a></li>
<li class="chapter" data-level="5.1.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#partial-f-test-for-additional-variables"><i class="fa fa-check"></i><b>5.1.2</b> Partial F test for additional variable(s)</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#testing-the-partial-regression-coefficients"><i class="fa fa-check"></i><b>5.2</b> Testing the Partial Regression Coefficients</a></li>
<li class="chapter" data-level="5.3" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#partial-and-semi-paritial-part-correlations"><i class="fa fa-check"></i><b>5.3</b> Partial and Semi-paritial (Part) Correlations</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#r-syntax-3"><i class="fa fa-check"></i><b>5.3.1</b> R Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#sum-up"><i class="fa fa-check"></i><b>5.3.2</b> Sum up</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#a-complete-example-1"><i class="fa fa-check"></i><b>5.4</b> A Complete Example</a></li>
<li class="chapter" data-level="5.5" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#types-of-multiple-regression"><i class="fa fa-check"></i><b>5.5</b> Types of Multiple Regression</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#regression-model-selection-based-on-statistics"><i class="fa fa-check"></i><b>5.5.1</b> Regression model selection based on statistics</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#a-few-assumptions-in-regression"><i class="fa fa-check"></i><b>5.6</b> (A Few) Assumptions in Regression</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#linearity"><i class="fa fa-check"></i><b>5.6.1</b> Linearity</a></li>
<li class="chapter" data-level="5.6.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#homoscedasticity-constant-variance-assumption"><i class="fa fa-check"></i><b>5.6.2</b> Homoscedasticity (Constant Variance Assumption)</a></li>
<li class="chapter" data-level="5.6.3" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#normality"><i class="fa fa-check"></i><b>5.6.3</b> Normality</a></li>
<li class="chapter" data-level="5.6.4" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#independence-of-residuals"><i class="fa fa-check"></i><b>5.6.4</b> Independence of Residuals</a></li>
<li class="chapter" data-level="5.6.5" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#multicollinearity"><i class="fa fa-check"></i><b>5.6.5</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#multiple-regression-and-patterns-of-association"><i class="fa fa-check"></i><b>5.7</b> Multiple Regression and Patterns of Association</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#complete-independence"><i class="fa fa-check"></i><b>5.7.1</b> Complete independence</a></li>
<li class="chapter" data-level="5.7.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#partial-redundancy"><i class="fa fa-check"></i><b>5.7.2</b> Partial redundancy</a></li>
<li class="chapter" data-level="5.7.3" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#complete-redundancy"><i class="fa fa-check"></i><b>5.7.3</b> Complete redundancy</a></li>
<li class="chapter" data-level="5.7.4" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#suppression-in-multiple-regression"><i class="fa fa-check"></i><b>5.7.4</b> Suppression in multiple regression</a></li>
<li class="chapter" data-level="5.7.5" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#summary-of-patterns-of-association"><i class="fa fa-check"></i><b>5.7.5</b> Summary of patterns of association</a></li>
<li class="chapter" data-level="5.7.6" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#statistical-paradoxes"><i class="fa fa-check"></i><b>5.7.6</b> Statistical paradoxes</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#regression-diagnostics"><i class="fa fa-check"></i><b>5.8</b> Regression Diagnostics</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#leverage"><i class="fa fa-check"></i><b>5.8.1</b> Leverage</a></li>
<li class="chapter" data-level="5.8.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#discrepancy"><i class="fa fa-check"></i><b>5.8.2</b> Discrepancy</a></li>
<li class="chapter" data-level="5.8.3" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#influence"><i class="fa fa-check"></i><b>5.8.3</b> Influence</a></li>
<li class="chapter" data-level="5.8.4" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#sources-of-outliers-and-remedies"><i class="fa fa-check"></i><b>5.8.4</b> Sources of Outliers and Remedies</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#curvilinear-regression"><i class="fa fa-check"></i><b>5.9</b> Curvilinear Regression</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#polynomial-regression"><i class="fa fa-check"></i><b>5.9.1</b> Polynomial regression</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#useful-functions-and-symbols-commonly-used-in-r-when-fitting-linear-models"><i class="fa fa-check"></i><b>5.10</b> Useful Functions and Symbols Commonly Used in R When Fitting Linear Models</a></li>
<li class="chapter" data-level="5.11" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#interactions-in-regression"><i class="fa fa-check"></i><b>5.11</b> Interactions in Regression</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#an-example-1"><i class="fa fa-check"></i><b>5.11.1</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#categorical-independent-variables"><i class="fa fa-check"></i><b>5.12</b> Categorical Independent Variables</a>
<ul>
<li class="chapter" data-level="5.12.1" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#binary-independent-variables"><i class="fa fa-check"></i><b>5.12.1</b> Binary independent variables</a></li>
<li class="chapter" data-level="5.12.2" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#categorical-independent-variables-with-more-than-two-categories"><i class="fa fa-check"></i><b>5.12.2</b> Categorical independent variables with more than two categories</a></li>
<li class="chapter" data-level="5.12.3" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#an-example-2"><i class="fa fa-check"></i><b>5.12.3</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#interactions-between-categorical-and-continuous-variables"><i class="fa fa-check"></i><b>5.13</b> Interactions Between Categorical and Continuous Variables</a></li>
<li class="chapter" data-level="5.14" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#an-open-book-on-regression"><i class="fa fa-check"></i><b>5.14</b> An Open Book on Regression</a></li>
<li class="chapter" data-level="5.15" data-path="multiple-regression-analysis.html"><a href="multiple-regression-analysis.html#create-apa-tables-with-apatables-package"><i class="fa fa-check"></i><b>5.15</b> Create APA Tables with <code>apaTables</code> Package</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html"><i class="fa fa-check"></i><b>6</b> Binary Logistic Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#some-definitions"><i class="fa fa-check"></i><b>6.1</b> Some Definitions</a></li>
<li class="chapter" data-level="6.2" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#logarithm-rules"><i class="fa fa-check"></i><b>6.2</b> Logarithm Rules</a></li>
<li class="chapter" data-level="6.3" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#logistic-regression-equation"><i class="fa fa-check"></i><b>6.3</b> Logistic Regression Equation</a></li>
<li class="chapter" data-level="6.4" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#run-logistic-regression"><i class="fa fa-check"></i><b>6.4</b> Run Logistic Regression</a></li>
<li class="chapter" data-level="6.5" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#logistic-regression-coefficients"><i class="fa fa-check"></i><b>6.5</b> Logistic Regression Coefficients</a></li>
<li class="chapter" data-level="6.6" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#similarities-and-differences-between-binary-logistic-regression-and-ols-regression"><i class="fa fa-check"></i><b>6.6</b> Similarities and Differences Between Binary Logistic Regression and OLS Regression</a></li>
<li class="chapter" data-level="6.7" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#empirical-example"><i class="fa fa-check"></i><b>6.7</b> Empirical Example</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#assess-the-model---model-chi-square"><i class="fa fa-check"></i><b>6.7.1</b> Assess the model - model chi-square</a></li>
<li class="chapter" data-level="6.7.2" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#assess-the-model---r2"><i class="fa fa-check"></i><b>6.7.2</b> Assess the model - <span class="math inline">\({R^2}\)</span></a></li>
<li class="chapter" data-level="6.7.3" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#diagnostics"><i class="fa fa-check"></i><b>6.7.3</b> Diagnostics</a></li>
<li class="chapter" data-level="6.7.4" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#assumptions---linearity"><i class="fa fa-check"></i><b>6.7.4</b> Assumptions - Linearity</a></li>
<li class="chapter" data-level="6.7.5" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#assumptions---independence-of-errors"><i class="fa fa-check"></i><b>6.7.5</b> Assumptions - Independence of errors</a></li>
<li class="chapter" data-level="6.7.6" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#use-more-predictors"><i class="fa fa-check"></i><b>6.7.6</b> Use more predictors</a></li>
<li class="chapter" data-level="6.7.7" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#check-multicollinearity-among-ivs"><i class="fa fa-check"></i><b>6.7.7</b> Check Multicollinearity Among IVs</a></li>
<li class="chapter" data-level="6.7.8" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#interprete-results"><i class="fa fa-check"></i><b>6.7.8</b> Interprete results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>7</b> Analysis of Variance</a>
<ul>
<li class="chapter" data-level="7.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#historical-background"><i class="fa fa-check"></i><b>7.1</b> Historical Background</a></li>
<li class="chapter" data-level="7.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#the-general-linear-model-glm"><i class="fa fa-check"></i><b>7.2</b> The General Linear Model (GLM)</a></li>
<li class="chapter" data-level="7.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#one-way-anova-for-single-factor-designs"><i class="fa fa-check"></i><b>7.3</b> One-Way ANOVA (for Single Factor Designs)</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#statistical-hypotheses"><i class="fa fa-check"></i><b>7.3.1</b> Statistical hypotheses</a></li>
<li class="chapter" data-level="7.3.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#basic-idea-of-anova"><i class="fa fa-check"></i><b>7.3.2</b> Basic idea of ANOVA</a></li>
<li class="chapter" data-level="7.3.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#empirical-example-1"><i class="fa fa-check"></i><b>7.3.3</b> Empirical example</a></li>
<li class="chapter" data-level="7.3.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#pairwise-comparisons"><i class="fa fa-check"></i><b>7.3.4</b> Pairwise comparisons</a></li>
<li class="chapter" data-level="7.3.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#planned-comparisons"><i class="fa fa-check"></i><b>7.3.5</b> Planned comparisons</a></li>
<li class="chapter" data-level="7.3.6" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#post-hoc-pairwise-comparisons"><i class="fa fa-check"></i><b>7.3.6</b> Post-hoc pairwise comparisons</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#anova-assumptions"><i class="fa fa-check"></i><b>7.4</b> ANOVA Assumptions</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#robustness"><i class="fa fa-check"></i><b>7.4.1</b> Robustness</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#one-way-anova-using-glm-approach"><i class="fa fa-check"></i><b>7.5</b> One-way ANOVA Using GLM approach</a></li>
<li class="chapter" data-level="7.6" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#factorial-analysis-of-variance-factorial-anova"><i class="fa fa-check"></i><b>7.6</b> Factorial Analysis of Variance (Factorial ANOVA)</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#numerical-calcuations-for-two-way-anova"><i class="fa fa-check"></i><b>7.6.1</b> Numerical calcuations for two-way ANOVA</a></li>
<li class="chapter" data-level="7.6.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#partitioning-the-total-sum-of-squares"><i class="fa fa-check"></i><b>7.6.2</b> Partitioning the total sum of squares</a></li>
<li class="chapter" data-level="7.6.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#empirical-example---two-way-anova"><i class="fa fa-check"></i><b>7.6.3</b> Empirical example - Two-way ANOVA</a></li>
<li class="chapter" data-level="7.6.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#assumptions-for-factorial-anova-see-refanova-assumptions"><i class="fa fa-check"></i><b>7.6.4</b> Assumptions for factorial ANOVA (see @ref(anova-assumptions))</a></li>
<li class="chapter" data-level="7.6.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#contrasts-using-the-multcomp-package"><i class="fa fa-check"></i><b>7.6.5</b> Contrasts using the <code>multcomp</code> package</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#factorial-anova-as-multiple-regression"><i class="fa fa-check"></i><b>7.7</b> Factorial ANOVA as Multiple Regression</a></li>
<li class="chapter" data-level="7.8" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#a-blog-on-anova-in-r"><i class="fa fa-check"></i><b>7.8</b> A Blog on ANOVA in R</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>8</b> Analysis of Covariance</a>
<ul>
<li class="chapter" data-level="8.1" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#purposes-of-ancova"><i class="fa fa-check"></i><b>8.1</b> Purposes of ANCOVA</a></li>
<li class="chapter" data-level="8.2" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#choice-of-covariates-to-use"><i class="fa fa-check"></i><b>8.2</b> Choice of covariates to use</a></li>
<li class="chapter" data-level="8.3" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#statistical-model-for-ancova"><i class="fa fa-check"></i><b>8.3</b> Statistical Model for ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#ancova-assumptions"><i class="fa fa-check"></i><b>8.4</b> ANCOVA Assumptions</a></li>
<li class="chapter" data-level="8.5" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#empirical-example-2"><i class="fa fa-check"></i><b>8.5</b> Empirical Example</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#assumptions---normality"><i class="fa fa-check"></i><b>8.5.1</b> Assumptions - Normality</a></li>
<li class="chapter" data-level="8.5.2" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#assumptions---homogeneity-of-variance"><i class="fa fa-check"></i><b>8.5.2</b> Assumptions - Homogeneity of Variance</a></li>
<li class="chapter" data-level="8.5.3" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#assumptions---independence-of-the-covariate-and-the-independent-variable"><i class="fa fa-check"></i><b>8.5.3</b> Assumptions - Independence of the covariate and the independent variable</a></li>
<li class="chapter" data-level="8.5.4" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#assumptions---homogeneity-of-regression-slopes"><i class="fa fa-check"></i><b>8.5.4</b> Assumptions - Homogeneity of regression slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#post-hoc-tests-using-the-multcomp-package"><i class="fa fa-check"></i><b>8.6</b> Post-hoc Tests using the <code>multcomp</code> package</a></li>
<li class="chapter" data-level="8.7" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#ancova-as-a-glm"><i class="fa fa-check"></i><b>8.7</b> ANCOVA as a GLM</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html"><i class="fa fa-check"></i><b>9</b> Repeated Measures ANOVA and Mixed Designs</a>
<ul>
<li class="chapter" data-level="9.1" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#repeated-measures-anova"><i class="fa fa-check"></i><b>9.1</b> Repeated-Measures ANOVA</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#advantages-of-repeated-measures-design"><i class="fa fa-check"></i><b>9.1.1</b> Advantages of repeated-measures design</a></li>
<li class="chapter" data-level="9.1.2" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#disadvantages-of-repeated-measures-design"><i class="fa fa-check"></i><b>9.1.2</b> Disadvantages of repeated-measures design</a></li>
<li class="chapter" data-level="9.1.3" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#variance-partitioning-in-one-way-repeated-measures-design"><i class="fa fa-check"></i><b>9.1.3</b> Variance partitioning in one-way repeated measures design</a></li>
<li class="chapter" data-level="9.1.4" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#assumptions-in-repeated-measures-analysis"><i class="fa fa-check"></i><b>9.1.4</b> Assumptions in repeated measures analysis</a></li>
<li class="chapter" data-level="9.1.5" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#alternative-specification-of-the-variance-covariance-matrix"><i class="fa fa-check"></i><b>9.1.5</b> Alternative Specification of the Variance-Covariance Matrix</a></li>
<li class="chapter" data-level="9.1.6" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#empirical-example-3"><i class="fa fa-check"></i><b>9.1.6</b> Empirical example</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#mixed-designs"><i class="fa fa-check"></i><b>9.2</b> Mixed Designs</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#one-between-and-one-within-factor-design"><i class="fa fa-check"></i><b>9.2.1</b> One between and one within factor design</a></li>
<li class="chapter" data-level="9.2.2" data-path="repeated-measures-anova-and-mixed-designs.html"><a href="repeated-measures-anova-and-mixed-designs.html#a-few-online-resources"><i class="fa fa-check"></i><b>9.2.2</b> A few online resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="power-analysis.html"><a href="power-analysis.html"><i class="fa fa-check"></i><b>10</b> Power Analysis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="power-analysis.html"><a href="power-analysis.html#components-of-power-analysis"><i class="fa fa-check"></i><b>10.1</b> Components of Power Analysis</a></li>
<li class="chapter" data-level="10.2" data-path="power-analysis.html"><a href="power-analysis.html#effect-sizes"><i class="fa fa-check"></i><b>10.2</b> Effect Sizes</a></li>
<li class="chapter" data-level="10.3" data-path="power-analysis.html"><a href="power-analysis.html#types-of-power-analysis"><i class="fa fa-check"></i><b>10.3</b> Types of Power Analysis</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="power-analysis.html"><a href="power-analysis.html#a-priori-power-analysis"><i class="fa fa-check"></i><b>10.3.1</b> A priori power analysis</a></li>
<li class="chapter" data-level="10.3.2" data-path="power-analysis.html"><a href="power-analysis.html#post-hoc-power-analysis"><i class="fa fa-check"></i><b>10.3.2</b> Post-hoc power analysis</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="power-analysis.html"><a href="power-analysis.html#a-two-tailed-t-test-for-independent-samples-power-example"><i class="fa fa-check"></i><b>10.4</b> a Two-Tailed <em>t Test</em> for Independent Samples Power Example</a></li>
<li class="chapter" data-level="10.5" data-path="power-analysis.html"><a href="power-analysis.html#software"><i class="fa fa-check"></i><b>10.5</b> Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative Foundations in Educational Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="binary-logistic-regression" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Binary Logistic Regression</h1>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="binary-logistic-regression.html#cb311-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio); <span class="fu">library</span>(ggplot2); <span class="fu">library</span>(QuantPsyc); <span class="fu">library</span>(psych); <span class="fu">library</span>(car); <span class="fu">library</span>(reshape)</span></code></pre></div>
<p>Binary logistic regression is a form of regression which is used when the DV is a dichotomy and the IVs are of any type. It belongs to <strong>generalized</strong> linear models.</p>
<ul>
<li>For a binary DV, we have two possible outcomes. Let’s take a look at the <code>UCBAdmissions</code> dataset built into R.</li>
</ul>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="binary-logistic-regression.html#cb312-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View(UCBAdmissions)</span></span>
<span id="cb312-2"><a href="binary-logistic-regression.html#cb312-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(UCBAdmissions) <span class="co"># the dataset is a table</span></span></code></pre></div>
<pre><code>## [1] &quot;table&quot;</code></pre>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="binary-logistic-regression.html#cb314-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(UCBAdmissions) <span class="co"># convert the table to a data frame</span></span>
<span id="cb314-2"><a href="binary-logistic-regression.html#cb314-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(dat)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="binary-logistic-regression.html#cb316-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> reshape<span class="sc">::</span><span class="fu">untable</span>(<span class="at">df =</span> dat[, <span class="sc">!</span><span class="fu">names</span>(dat) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Freq&quot;</span>)], <span class="at">num=</span>dat<span class="sc">$</span>Freq)</span>
<span id="cb316-2"><a href="binary-logistic-regression.html#cb316-2" aria-hidden="true" tabindex="-1"></a><span class="co"># View(dat)</span></span></code></pre></div>
<p>Let’s answer the question: Is there a relationship between gender and admission? Alternatively, do males have a higher chance of being admitted than females? For now, let’s also recode the variables Admit and Gender to be numeric variables with “0”s and “1”s. For the Admit variable, Admitted = 1, Rejected = 0. For the Gender varable, 1 = Female, 0 = Male.</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="binary-logistic-regression.html#cb317-1" aria-hidden="true" tabindex="-1"></a>contingency_table1 <span class="ot">&lt;-</span> <span class="fu">table</span>(dat<span class="sc">$</span>Gender, dat<span class="sc">$</span>Admit) <span class="co"># contingency table. row is Gender; column is Admit</span></span>
<span id="cb317-2"><a href="binary-logistic-regression.html#cb317-2" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(contingency_table1)</span>
<span id="cb317-3"><a href="binary-logistic-regression.html#cb317-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(contingency_table1) <span class="co"># cell percentages</span></span>
<span id="cb317-4"><a href="binary-logistic-regression.html#cb317-4" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(contingency_table1, <span class="dv">1</span>) <span class="co"># row percentages</span></span>
<span id="cb317-5"><a href="binary-logistic-regression.html#cb317-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(contingency_table1, <span class="dv">2</span>) <span class="co"># column percentages</span></span></code></pre></div>
<pre><code>##         
##          Admitted Rejected  Sum
##   Male       1198     1493 2691
##   Female      557     1278 1835
##   Sum        1755     2771 4526
##         
##           Admitted  Rejected
##   Male   0.2646929 0.3298719
##   Female 0.1230667 0.2823685
##         
##           Admitted  Rejected
##   Male   0.4451877 0.5548123
##   Female 0.3035422 0.6964578
##         
##           Admitted  Rejected
##   Male   0.6826211 0.5387947
##   Female 0.3173789 0.4612053</code></pre>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="binary-logistic-regression.html#cb319-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Admit <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dat<span class="sc">$</span>Admit<span class="sc">==</span><span class="st">&quot;Admitted&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb319-2"><a href="binary-logistic-regression.html#cb319-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Gender <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dat<span class="sc">$</span>Gender<span class="sc">==</span><span class="st">&quot;Female&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb319-3"><a href="binary-logistic-regression.html#cb319-3" aria-hidden="true" tabindex="-1"></a>contingency_table2 <span class="ot">&lt;-</span> <span class="fu">table</span>(dat<span class="sc">$</span>Gender, dat<span class="sc">$</span>Admit) <span class="co"># contingency table. row is Gender; column is Admit</span></span>
<span id="cb319-4"><a href="binary-logistic-regression.html#cb319-4" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(contingency_table2)</span>
<span id="cb319-5"><a href="binary-logistic-regression.html#cb319-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x=</span>Gender, <span class="at">y=</span>Admit, <span class="at">color =</span> Gender)) <span class="sc">+</span> </span>
<span id="cb319-6"><a href="binary-logistic-regression.html#cb319-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="dv">0</span>, <span class="at">height=</span><span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb319-7"><a href="binary-logistic-regression.html#cb319-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb319-8"><a href="binary-logistic-regression.html#cb319-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-152-1.png" width="672" /></p>
<pre><code>##      
##          0    1  Sum
##   0   1493 1198 2691
##   1   1278  557 1835
##   Sum 2771 1755 4526</code></pre>
<div id="some-definitions" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Some Definitions</h2>
<ul>
<li><p><strong>Probability</strong> of an Event</p></li>
<li><p>Event = Being admitted to college</p></li>
<li><p>Probability of the event P(Admitted) = 0.6</p></li>
<li><p><strong>Odds</strong> of an Event</p>
<ul>
<li>Odds is the relative chance of an event</li>
<li>Odds of being admitted = <span class="math inline">\(\frac{{P(Admitted)}}{{1 - P(Admitted)}} = \frac{{.6}}{{.4}} = 1.5\)</span></li>
</ul></li>
<li><p>If you know the probability of an event, you can get the odds and vice versa.</p></li>
<li><p><strong>Logit</strong> = Log-Ods of an Event</p>
<ul>
<li>Logit is the <em>logarithm</em> of the odds. Logit = log(odds)</li>
<li>Odds of being admitted = <span class="math inline">\(\frac{{P(Admitted)}}{{1 - P(Admitted)}} = \frac{{.6}}{{.4}} = 1.5\)</span></li>
<li>Logit of being admitted =
<span class="math inline">\({\log _e}(Odds(Admitted)) = {\log _e}(1.5) = .405\)</span></li>
</ul></li>
<li><p>If you know the one of the three: probability, odds, and logit, you can get the values for the other two.</p></li>
</ul>
</div>
<div id="logarithm-rules" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Logarithm Rules</h2>
<p><span class="math display">\[{\log _b}(XY) = {\log _b}(X) + {\log _b}(Y)\]</span>
<span class="math display">\[{\log _b}(\frac{X}{Y}) = {\log _b}(X) - {\log _b}(Y)\]</span>
<span class="math display">\[{\log _b}({X^k}) = k{\log _b}(X)\]</span>
<span class="math display">\[{\log _b}(1) = 0\]</span>
<span class="math display">\[{\log _b}(b) = 1\]</span></p>
<p><span class="math display">\[{\log _b}({b^k}) = k\]</span>
<span class="math display">\[{b^{{{\log }_b}(k)}} = k\]</span></p>
<p><strong>Given <span class="math inline">\({\log _e}(A) = 1.5\)</span>, what is <em>A</em>?</strong></p>
<p><span class="math inline">\(A = {e^{{{\log }_e}(A)}} = {e^{1.5}} = {(2.718282)^{1.5}}\)</span> where <span class="math inline">\(e\)</span> is a mathematical constant often called Euler’s (pronounced “Oiler”) number.</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="binary-logistic-regression.html#cb321-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>## [1] 4.481689</code></pre>
<p><strong>Given logit = 3, what is the odds?</strong></p>
<p>logit = <span class="math inline">\({\log _e}(Odds) = 3\)</span></p>
<p><span class="math inline">\(Odds = {e^3}\)</span></p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="binary-logistic-regression.html#cb323-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 20.08554</code></pre>
</div>
<div id="logistic-regression-equation" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Logistic Regression Equation</h2>
<p><strong>Regular OLS Regression</strong>
<span class="math display">\[Y = a + bX + e\]</span>
<span class="math display">\[\hat Y = a + bX\]</span></p>
<p><strong>Logistic Regression</strong>
<span class="math display">\[{\rm{logit}} = a + bX\]</span>
<span class="math display">\[Odds = {e^{(a + bX)}}\]</span>
<span class="math display">\[P(Y = 1) = \frac{{{e^{a + bX}}}}{{1 + {e^{a + bX}}}} = \frac{1}{{1 + {e^{ - (a + bX)}}}}\]</span></p>
</div>
<div id="run-logistic-regression" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Run Logistic Regression</h2>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="binary-logistic-regression.html#cb325-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Admit <span class="sc">~</span> Gender, <span class="at">family =</span> binomial, <span class="at">data =</span> dat)</span>
<span id="cb325-2"><a href="binary-logistic-regression.html#cb325-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Admit ~ Gender, family = binomial, data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0855  -1.0855  -0.8506   1.2722   1.5442  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.22013    0.03879  -5.675 1.38e-08 ***
## Gender      -0.61035    0.06389  -9.553  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 6044.3  on 4525  degrees of freedom
## Residual deviance: 5950.9  on 4524  degrees of freedom
## AIC: 5954.9
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="binary-logistic-regression.html#cb327-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model)</span>
<span id="cb327-2"><a href="binary-logistic-regression.html#cb327-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code></pre></div>
<pre><code>##     Admit Gender Dept      prob
## 1       1      0    A 0.4451877
## 1.1     1      0    A 0.4451877
## 1.2     1      0    A 0.4451877
## 1.3     1      0    A 0.4451877
## 1.4     1      0    A 0.4451877
## 1.5     1      0    A 0.4451877</code></pre>
</div>
<div id="logistic-regression-coefficients" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Logistic Regression Coefficients</h2>
<p><img src="image/logistic_regression_coefficient_gender.png" width="150%" /></p>
<p><span class="math inline">\({\log _e}(\frac{{P(Admitted)}}{{1 - P(Admitted)}}) = - 0.22 - 0.61*Gender\)</span></p>
<ul>
<li>The outcome is the logit!</li>
<li>Which group (male vs. female) has a higher logit value?</li>
<li>How to interprete?
<ul>
<li>“The logit of the female group is 0.61 lower than the logit of the male group.”</li>
</ul></li>
<li>What does this mean?</li>
</ul>
<p><span class="math inline">\(- 0.61 = {\rm{logit}}(Female) - {\rm{logit}}(Male)\)</span></p>
<p><span class="math inline">\({\rm{ }} = {\log _e}[Odds(Female)] - {\log _e}[Odds(Male)]\)</span></p>
<p><span class="math inline">\({\rm{ }} = {\log _e}[\frac{{Odds(Female)}}{{Odds(Male)}}]\)</span></p>
<p>Therefore, <span class="math inline">\(\frac{{Odds(Female)}}{{Odds(Male)}} = \exp (- 0.61) = 0.54\)</span></p>
<p>This is called <strong>Odds Ratio</strong>. Odds Ratio is the ratio of odds of a comparison/treatment group to that of the reference/control group.</p>
<p><strong>Note</strong>: For the <code>UCBAdmissions</code> data, if you conduct a binary logistic regression model for each department separately, you may reach different conclusions regarding gender differences in college admissions. Google .blue[<em>Simpson’s paradox</em>] to learn more.</p>
</div>
<div id="similarities-and-differences-between-binary-logistic-regression-and-ols-regression" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Similarities and Differences Between Binary Logistic Regression and OLS Regression</h2>
<p><strong>Similarities</strong></p>
<ul>
<li>IVs can be continuous, categorical, or a combination of continuous and categorical variables.</li>
<li>Many of the essential concepts in OLS regression still apply to logistic regression.
<ul>
<li>Model comparison and selection</li>
<li>Assumptions (Independence of Errors, Linearity, Multicollinearity; but <strong>NOT</strong> Normality)</li>
<li>Diagnostics (Leverage, Discrepancy, Influence)</li>
</ul></li>
</ul>
<p><strong>Differences</strong></p>
<ul>
<li>DV is categorical in logistic regression</li>
<li>The DV in logistic regression follows a Binomial distribution for which you can specify a link function (logit and probit are two commonly used link functions)</li>
<li>The estimation method for logistic regression is maximum likelihood, rather than OLS.</li>
</ul>
</div>
<div id="empirical-example" class="section level2" number="6.7">
<h2><span class="header-section-number">6.7</span> Empirical Example</h2>
<p><a href="https://en.wikipedia.org/wiki/Framingham_Heart_Study">The Framingham Heart Study</a></p>
<ul>
<li><p>DV : Coronary Heart Disease (TenYearCHD, yes=1; no=0) status was collected 10 years after the first exam.</p></li>
<li><p>IVs were collected in the first data collection</p>
<ul>
<li>Demographic factors
<ul>
<li>male(male = 1, female = 0)</li>
<li>age (in years)</li>
<li>education (Some high school=1, high school/GED=2; some college/vocational school=3; college=4)</li>
</ul></li>
<li>Behavioral risk factors
<ul>
<li>currentSmoker (smoker=1, non smoker=0)</li>
<li>cigsPerDay</li>
</ul></li>
<li>Medical history risk factors
<ul>
<li>BPmeds (On blood pressure medication at time of first exam)</li>
<li>prevalentStroker (Previously had a stroke)</li>
<li>prevalentHyp (Current hypertension/high blood pressure)</li>
<li>diabetes (currently has diabetes)</li>
</ul></li>
<li>Risk factors from first examination
<ul>
<li>totChol (Total cholesterol, mg/dL)</li>
<li>sysBP (Systolic blood pressure)</li>
<li>diaBP (Diastolic blood pressure)</li>
<li>BMI (Body Mass Index, weight (kg)/height (m^2))</li>
<li>heartRate (Heart rate, beats/minute)</li>
<li>glucose (Blood glucose level, mg/dL)</li>
</ul></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="binary-logistic-regression.html#cb329-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">&quot;data/framingham.csv&quot;</span>)</span>
<span id="cb329-2"><a href="binary-logistic-regression.html#cb329-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> age, <span class="at">family =</span> binomial, <span class="at">data =</span> dat)</span>
<span id="cb329-3"><a href="binary-logistic-regression.html#cb329-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = TenYearCHD ~ age, family = binomial, data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0386  -0.6261  -0.4580  -0.3695   2.4493  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -5.561090   0.283746  -19.60   &lt;2e-16 ***
## age          0.074650   0.005265   14.18   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3612.2  on 4239  degrees of freedom
## Residual deviance: 3396.6  on 4238  degrees of freedom
## AIC: 3400.6
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><strong>Regression Coefficient</strong>
<img src="image/logistic_regression_coefficient_CHD_age.png" width="150%" /></p>
<p><strong>Odds Ratios and Confidence Intervals</strong></p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="binary-logistic-regression.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(model<span class="sc">$</span>coefficients)</span></code></pre></div>
<pre><code>## (Intercept)         age 
## 0.003844584 1.077507075</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="binary-logistic-regression.html#cb333-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(model))</span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 0.002190705 0.006664767
## age         1.066517962 1.088765650</code></pre>
<ul>
<li>One year increase in age is related to 0.075 increase in the logit of having CHD</li>
<li>Given logit = 0.075, we obtain exp(0.055) = 1.08</li>
<li>One year increase in age changes the odds of CHD from 1 to 1.08</li>
</ul>
<p><strong>To Obtain Probabilities</strong></p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="binary-logistic-regression.html#cb335-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model) <span class="co">#&lt;&lt;</span></span>
<span id="cb335-2"><a href="binary-logistic-regression.html#cb335-2" aria-hidden="true" tabindex="-1"></a>df_low_prob <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>age <span class="sc">&lt;</span> <span class="dv">40</span>, ]</span>
<span id="cb335-3"><a href="binary-logistic-regression.html#cb335-3" aria-hidden="true" tabindex="-1"></a>df_mid_prob <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>age <span class="sc">&gt;</span><span class="dv">45</span> <span class="sc">&amp;</span> dat<span class="sc">$</span>age <span class="sc">&lt;</span><span class="dv">55</span>, ]</span>
<span id="cb335-4"><a href="binary-logistic-regression.html#cb335-4" aria-hidden="true" tabindex="-1"></a>df_high_prob <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>age <span class="sc">&gt;</span><span class="dv">65</span>,]</span>
<span id="cb335-5"><a href="binary-logistic-regression.html#cb335-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>prob)) <span class="sc">+</span></span>
<span id="cb335-6"><a href="binary-logistic-regression.html#cb335-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb335-7"><a href="binary-logistic-regression.html#cb335-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> df_low_prob, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb335-8"><a href="binary-logistic-regression.html#cb335-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> df_mid_prob, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb335-9"><a href="binary-logistic-regression.html#cb335-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> df_high_prob, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-161-1.png" width="672" /></p>
<p><strong>The relationship between age and CHD is positive but not linear.</strong></p>
<div id="assess-the-model---model-chi-square" class="section level3" number="6.7.1">
<h3><span class="header-section-number">6.7.1</span> Assess the model - model chi-square</h3>
<p>How much better does the model predict the outcome variable, compared to a baseline model?</p>
<ul>
<li><strong>log-likelihood</strong> of the model. Analogous to the residual sum of squares in OLS regression</li>
<li><strong>deviance</strong> = -2 X log-likelihood. It has a chi-square distribution.</li>
<li><strong>model chi-square statistic</strong>. Difference between the deviance of the baseline model and the deviance of the current model.</li>
</ul>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="binary-logistic-regression.html#cb336-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(model)</span></span>
<span id="cb336-2"><a href="binary-logistic-regression.html#cb336-2" aria-hidden="true" tabindex="-1"></a>model.chisq <span class="ot">&lt;-</span> model<span class="sc">$</span>null.deviance <span class="sc">-</span> model<span class="sc">$</span>deviance</span>
<span id="cb336-3"><a href="binary-logistic-regression.html#cb336-3" aria-hidden="true" tabindex="-1"></a>chisq.df <span class="ot">&lt;-</span> model<span class="sc">$</span>df.null <span class="sc">-</span> model<span class="sc">$</span>df.residual</span>
<span id="cb336-4"><a href="binary-logistic-regression.html#cb336-4" aria-hidden="true" tabindex="-1"></a>(chisq.prob <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(model.chisq, chisq.df)) <span class="co"># right tailed</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
</div>
<div id="assess-the-model---r2" class="section level3" number="6.7.2">
<h3><span class="header-section-number">6.7.2</span> Assess the model - <span class="math inline">\({R^2}\)</span></h3>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="binary-logistic-regression.html#cb338-1" aria-hidden="true" tabindex="-1"></a>logisticPseudoR2s <span class="ot">&lt;-</span> <span class="cf">function</span>(LogModel) {</span>
<span id="cb338-2"><a href="binary-logistic-regression.html#cb338-2" aria-hidden="true" tabindex="-1"></a>  dev <span class="ot">&lt;-</span> LogModel<span class="sc">$</span>deviance</span>
<span id="cb338-3"><a href="binary-logistic-regression.html#cb338-3" aria-hidden="true" tabindex="-1"></a>  nullDev <span class="ot">&lt;-</span> LogModel<span class="sc">$</span>null.deviance</span>
<span id="cb338-4"><a href="binary-logistic-regression.html#cb338-4" aria-hidden="true" tabindex="-1"></a>  modelN <span class="ot">&lt;-</span> <span class="fu">length</span>(LogModel<span class="sc">$</span>fitted.values)</span>
<span id="cb338-5"><a href="binary-logistic-regression.html#cb338-5" aria-hidden="true" tabindex="-1"></a>  R<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>dev<span class="sc">/</span>nullDev</span>
<span id="cb338-6"><a href="binary-logistic-regression.html#cb338-6" aria-hidden="true" tabindex="-1"></a>  R.cs <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>(nullDev<span class="sc">-</span>dev)<span class="sc">/</span>modelN)</span>
<span id="cb338-7"><a href="binary-logistic-regression.html#cb338-7" aria-hidden="true" tabindex="-1"></a>  R.n <span class="ot">&lt;-</span> R.cs<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span>(nullDev<span class="sc">/</span>modelN))))</span>
<span id="cb338-8"><a href="binary-logistic-regression.html#cb338-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;PseudoR^2 for logistic regression</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb338-9"><a href="binary-logistic-regression.html#cb338-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;Hosmer &amp; Lemeshow R^2: &quot;</span>, <span class="fu">round</span>(R<span class="fl">.1</span>, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb338-10"><a href="binary-logistic-regression.html#cb338-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;Cox &amp; Snell R^2: &quot;</span>, <span class="fu">round</span>(R.cs, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb338-11"><a href="binary-logistic-regression.html#cb338-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;Naelkerke R^2: &quot;</span>, <span class="fu">round</span>(R.n, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb338-12"><a href="binary-logistic-regression.html#cb338-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb338-13"><a href="binary-logistic-regression.html#cb338-13" aria-hidden="true" tabindex="-1"></a><span class="fu">logisticPseudoR2s</span>(model)</span></code></pre></div>
<pre><code>## PseudoR^2 for logistic regression
## Hosmer &amp; Lemeshow R^2:  0.06 
## Cox &amp; Snell R^2:  0.05 
## Naelkerke R^2:  0.086</code></pre>
</div>
<div id="diagnostics" class="section level3" number="6.7.3">
<h3><span class="header-section-number">6.7.3</span> Diagnostics</h3>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="binary-logistic-regression.html#cb340-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>leverage <span class="ot">&lt;-</span> <span class="fu">hatvalues</span>(model) <span class="co"># leverage</span></span>
<span id="cb340-2"><a href="binary-logistic-regression.html#cb340-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>studentized.residuals <span class="ot">&lt;-</span> <span class="fu">rstudent</span>(model) <span class="co"># discrepancy</span></span>
<span id="cb340-3"><a href="binary-logistic-regression.html#cb340-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>cooks.d <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(model)  <span class="co"># influence</span></span>
<span id="cb340-4"><a href="binary-logistic-regression.html#cb340-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>leverage[(dat<span class="sc">$</span>leverage <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">*</span> <span class="fu">mean</span>(dat<span class="sc">$</span>leverage))] </span></code></pre></div>
<pre><code>##   [1] 0.001661901 0.001459850 0.001459850 0.001661901 0.001459850 0.001459850 0.001661901 0.001661901 0.001459850 0.001661901 0.001880347
##  [12] 0.001661901 0.001661901 0.001880347 0.001459850 0.001459850 0.001661901 0.001459850 0.001661901 0.001661901 0.001661901 0.001459850
##  [23] 0.001880347 0.001459850 0.001459850 0.001459850 0.001661901 0.001661901 0.001661901 0.001459850 0.001661901 0.001661901 0.001880347
##  [34] 0.001661901 0.001459850 0.001459850 0.001880347 0.001459850 0.001459850 0.001661901 0.001661901 0.001661901 0.001661901 0.001661901
##  [45] 0.001459850 0.002362781 0.001459850 0.001459850 0.001661901 0.001459850 0.001459850 0.001661901 0.001459850 0.001661901 0.001880347
##  [56] 0.001459850 0.001661901 0.001459850 0.001459850 0.001459850 0.001459850 0.001459850 0.001661901 0.001661901 0.001880347 0.001661901
##  [67] 0.001661901 0.001459850 0.001880347 0.001661901 0.001880347 0.001661901 0.001661901 0.001880347 0.001661901 0.001661901 0.001661901
##  [78] 0.001880347 0.001459850 0.002114350 0.001661901 0.002362781 0.001661901 0.001459850 0.002114350 0.002114350 0.001459850 0.001459850
##  [89] 0.001880347 0.001459850 0.001661901 0.001880347 0.001661901 0.001459850 0.001880347 0.002114350 0.001661901 0.001661901 0.001880347
## [100] 0.001880347 0.001661901 0.001880347 0.001661901 0.001459850 0.001459850 0.002114350 0.002114350 0.001661901 0.002114350 0.001880347</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="binary-logistic-regression.html#cb342-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>studentized.residuals[<span class="fu">abs</span>(dat<span class="sc">$</span>studentized.residuals) <span class="sc">&gt;</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="binary-logistic-regression.html#cb344-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>cooks.d[dat<span class="sc">$</span>cooks.d<span class="sc">&gt;</span><span class="dv">1</span>]</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="binary-logistic-regression.html#cb346-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>studentized.residuals[(<span class="fu">abs</span>(dat<span class="sc">$</span>studentized.residuals) <span class="sc">&gt;</span> <span class="dv">3</span>)]</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="binary-logistic-regression.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(model)</span></code></pre></div>
<pre><code>## No Studentized residuals with Bonferroni p &lt; 0.05
## Largest |rstudent|:
##     rstudent unadjusted p-value Bonferroni p
## 782 2.451316           0.014234           NA</code></pre>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="binary-logistic-regression.html#cb350-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>cooks.d[dat<span class="sc">$</span>cooks.d <span class="sc">&gt;</span><span class="dv">1</span>]</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
</div>
<div id="assumptions---linearity" class="section level3" number="6.7.4">
<h3><span class="header-section-number">6.7.4</span> Assumptions - Linearity</h3>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="binary-logistic-regression.html#cb352-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>log.age.Int <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>age)<span class="sc">*</span>dat<span class="sc">$</span>age <span class="co">#&lt;&lt;</span></span>
<span id="cb352-2"><a href="binary-logistic-regression.html#cb352-2" aria-hidden="true" tabindex="-1"></a>model.linearity <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> age <span class="sc">+</span> dat<span class="sc">$</span>log.age.Int, <span class="at">data =</span> dat, <span class="at">family =</span> <span class="fu">binomial</span>()) <span class="co">#&lt;&lt;</span></span>
<span id="cb352-3"><a href="binary-logistic-regression.html#cb352-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.linearity)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = TenYearCHD ~ age + dat$log.age.Int, family = binomial(), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.9096  -0.6538  -0.4639  -0.3403   2.5935  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -13.45767    3.46917  -3.879 0.000105 ***
## age               0.83681    0.33290   2.514 0.011947 *  
## dat$log.age.Int  -0.15396    0.06721  -2.291 0.021975 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3612.2  on 4239  degrees of freedom
## Residual deviance: 3391.2  on 4237  degrees of freedom
## AIC: 3397.2
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="assumptions---independence-of-errors" class="section level3" number="6.7.5">
<h3><span class="header-section-number">6.7.5</span> Assumptions - Independence of errors</h3>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="binary-logistic-regression.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dwt</span>(model)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.02687873      1.946162   0.074
##  Alternative hypothesis: rho != 0</code></pre>
</div>
<div id="use-more-predictors" class="section level3" number="6.7.6">
<h3><span class="header-section-number">6.7.6</span> Use more predictors</h3>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="binary-logistic-regression.html#cb356-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>edu.c <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>education)</span>
<span id="cb356-2"><a href="binary-logistic-regression.html#cb356-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dat<span class="sc">$</span>edu.c) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;some high school&quot;</span>, <span class="st">&quot;high school/GED&quot;</span>, <span class="st">&quot;some college/vocational&quot;</span>, <span class="st">&quot;college&quot;</span>)</span>
<span id="cb356-3"><a href="binary-logistic-regression.html#cb356-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> age <span class="sc">+</span> male <span class="sc">+</span> sysBP <span class="sc">+</span> edu.c, <span class="at">family =</span> binomial, <span class="at">data =</span> dat)</span>
<span id="cb356-4"><a href="binary-logistic-regression.html#cb356-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = TenYearCHD ~ age + male + sysBP + edu.c, family = binomial, 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5951  -0.5995  -0.4423  -0.3124   2.8506  
## 
## Coefficients:
##                               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                  -7.427112   0.379871 -19.552  &lt; 2e-16 ***
## age                           0.058923   0.005893   9.999  &lt; 2e-16 ***
## male                          0.612284   0.093217   6.568 5.09e-11 ***
## sysBP                         0.017947   0.002002   8.967  &lt; 2e-16 ***
## edu.chigh school/GED         -0.179544   0.114138  -1.573    0.116    
## edu.csome college/vocational -0.100398   0.136901  -0.733    0.463    
## edu.ccollege                 -0.007083   0.151157  -0.047    0.963    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3522.6  on 4134  degrees of freedom
## Residual deviance: 3186.8  on 4128  degrees of freedom
##   (105 observations deleted due to missingness)
## AIC: 3200.8
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="check-multicollinearity-among-ivs" class="section level3" number="6.7.7">
<h3><span class="header-section-number">6.7.7</span> Check Multicollinearity Among IVs</h3>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="binary-logistic-regression.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model2)</span></code></pre></div>
<pre><code>##           GVIF Df GVIF^(1/(2*Df))
## age   1.167782  1        1.080640
## male  1.054028  1        1.026659
## sysBP 1.144721  1        1.069916
## edu.c 1.077856  3        1.012574</code></pre>
</div>
<div id="interprete-results" class="section level3" number="6.7.8">
<h3><span class="header-section-number">6.7.8</span> Interprete results</h3>
<p><strong>Regression Coefficients</strong>
<img src="image/logistic_regression_coefficients_CHD.png" width="360" /></p>
<p><strong>Odds Ratios and Confidence Intervals</strong></p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="binary-logistic-regression.html#cb360-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(model2<span class="sc">$</span>coefficients)</span></code></pre></div>
<pre><code>##                  (Intercept)                          age                         male                        sysBP         edu.chigh school/GED 
##                 0.0005949034                 1.0606932534                 1.8446390825                 1.0181093723                 0.8356510686 
## edu.csome college/vocational                 edu.ccollege 
##                 0.9044777525                 0.9929417559</code></pre>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="binary-logistic-regression.html#cb362-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(model2))</span></code></pre></div>
<pre><code>##                                     2.5 %      97.5 %
## (Intercept)                  0.0002801087 0.001242352
## age                          1.0485587804 1.073069542
## male                         1.5372823946 2.215676632
## sysBP                        1.0141309942 1.022122846
## edu.chigh school/GED         0.6670598320 1.043750212
## edu.csome college/vocational 0.6888360992 1.178746245
## edu.ccollege                 0.7343253293 1.329077617</code></pre>
<ul>
<li>Coefficient for “male.”
<ul>
<li>A male is more likely to have CHD than a female adjusting for the effects of other variables.</li>
<li>The odds of having CHD for a male is predicted to be 1.85 ( <span class="math inline">\({e^{0.612}}\)</span>) times the odds of of having CHD for a female, holding the other variables constant.</li>
</ul></li>
<li>Coefficient for “age.”
<ul>
<li>The older the person grew, the more likely the person would have CHD.</li>
<li>The odds of having CHD is predicted to increase by a factor of 1.06 ( <span class="math inline">\({e^{0.0589}}\)</span>) with one year increase in age, holding the other variables constant.</li>
</ul></li>
<li>Coefficients for the coded dummy variables for education.
<ul>
<li>None of them was statistically significant. Education level was not statistically significantly associated with the odds of having CHD, holding the other variables constant.</li>
<li><em>If</em> they were statistically significant, a person who finished high school is less likely to have CHD than a person who only had some high school eduation, holding the other variables constant. The odds of having CHD for a person who finished high school is predicted to decrease by a factor of 0.835( <span class="math inline">\({e^{-.180}}\)</span>) than a person who only had some high school education, holding the other variables constant.</li>
<li>The coefficients for the dummy variables compare one group’s odds of having CHD with the odds of the reference group (i.e., those with some high school education).</li>
</ul></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-regression-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-of-variance.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
